#5 :- 0000101 int8
- Numpy multidimentional Array
- Faster to read less bytes of memory
- No type checking when iterating through objects
- Single type
- Numpy uses contigous memory so accessing elements quickly.

In [2]:
import numpy as np

## BASICS

In [17]:
a = np.array([1,2,3], dtype= 'int16')
print(a)

[1 2 3]


In [18]:
type(a)

numpy.ndarray

In [19]:
len(a)

3

In [20]:
a.shape

(3,)

In [21]:
b = np.array([[9.0,8.0,7.0],[6.0,5,4]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [22]:
# Get Dimension
a.ndim

1

In [23]:
b.ndim

2

In [24]:
a.shape

(3,)

In [25]:
b.shape

(2, 3)

In [26]:
# Get Type
a.dtype

dtype('int16')

In [27]:
# Get Size
a.itemsize

2

In [28]:
#Get total size
a.nbytes

6

# Accessing/Changing specific elements, rows, columns, etc.

In [30]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
a.shape

(2, 4)

In [32]:
# Get a specific element [r,c]
a[1,3] #8

8

In [33]:
a[0,-2] #3

3

In [34]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4])

In [36]:
a[:,2]

array([3, 7])

In [37]:
#[startindex:endindex:stepsize]

In [47]:
a[::-1,::-1]

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [48]:
a[0, 1::2]

array([2, 4])

In [49]:
a[1,3] = 9

In [50]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [52]:
a[:,2] = 5
a

array([[1, 2, 5, 4],
       [5, 6, 5, 9]])

In [53]:
a[:,3] = [10,11]
a

array([[ 1,  2,  5, 10],
       [ 5,  6,  5, 11]])